events {
    worker_connections 1024;
}

http {
    server {
        listen 3000;

        # Redirigir la ruta /rest/v1/ de @supabase/supabase-js a PostgREST
        location /rest/v1/ {
            proxy_pass http://postgrest:3000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Redirigir cualquier otra consulta directamente a PostgREST
        location / {
            proxy_pass http://postgrest:3000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
